services:
  app0:
    image: web-app
    build: ./app
    environment:
      - POD_NUMBER=0
  
  app1:
    image: web-app
    depends_on:
      - app0
    environment:
      - POD_NUMBER=1

  app2:
    image: web-app
    depends_on:
      - app0
    environment:
      - POD_NUMBER=2
  
  web:
    image: nginx
    volumes:
    - ./load-balance:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80
    depends_on:
    - app0
    - app1
    - app2